// packages/core/react/index.esm.js
import PagiflowCore from 'pagiflow';
import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import React, { forwardRef, isValidElement, useRef, useState, useCallback, useEffect, useImperativeHandle, Children } from 'react';

/******************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
/* global Reflect, Promise, SuppressedError, Symbol, Iterator */


function __rest(s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
}

typeof SuppressedError === "function" ? SuppressedError : function (error, suppressed, message) {
    var e = new Error(message);
    return e.name = "SuppressedError", e.error = error, e.suppressed = suppressed, e;
};

// ─── Pagiflow loader (same as hook, kept local to avoid circular) ─────────────
function getPagiflow$1() {
    var _a;
    if (typeof window !== 'undefined' && window.Pagiflow) {
        return window.Pagiflow;
    }
    return ((_a = PagiflowCore.default) !== null && _a !== void 0 ? _a : PagiflowCore);
}
function initPagiflowFromElement$1(ctor, el, opts) {
    const attrValue = `pf-${Math.random().toString(36).slice(2)}`;
    const selector = `[data-pagiflow-react-id="${attrValue}"]`;
    el.setAttribute('data-pagiflow-react-id', attrValue);
    const bySelector = ctor(selector, opts);
    if (!bySelector) {
        el.removeAttribute('data-pagiflow-react-id');
        return null;
    }
    return bySelector;
}
// ─── Slot Component for asChild pattern ──────────────────────────────────────────
const Slot = forwardRef((_a, ref) => {
    var { children } = _a, props = __rest(_a, ["children"]);
    if (isValidElement(children)) {
        const clonedProps = Object.assign(Object.assign(Object.assign({}, props), children.props), { style: Object.assign(Object.assign({}, props.style), children.props.style), className: [props.className, children.props.className].filter(Boolean).join(' ') || undefined });
        const childRef = children.ref;
        if (ref || childRef) {
            clonedProps.ref = (node) => {
                if (typeof childRef === 'function')
                    childRef(node);
                else if (childRef && 'current' in childRef)
                    childRef.current = node;
                if (typeof ref === 'function')
                    ref(node);
                else if (ref && 'current' in ref)
                    ref.current = node;
            };
        }
        return React.cloneElement(children, clonedProps);
    }
    return null;
});
Slot.displayName = 'Slot';
/**
 * Wrapper for individual slides. Each direct child of `<Pagiflow>` becomes
 * a slide. By default (`asChild: true`), this acts as a Slot and merges
 * its props into the child element to avoid an extra wrapper `<div>`.
 * Pass `asChild={false}` to explicitly render a wrapper `<div>`.
 */
const PagiflowSlide = forwardRef((_a, ref) => {
    var { children, className, style, asChild = true } = _a, rest = __rest(_a, ["children", "className", "style", "asChild"]);
    const Comp = asChild && isValidElement(children) ? Slot : 'div';
    return (jsx(Comp, Object.assign({ ref: ref, className: className, style: style }, rest, { children: children })));
});
PagiflowSlide.displayName = 'PagiflowSlide';
// ─── <Pagiflow> component ─────────────────────────────────────────────────────
/**
 * Drop-in React component wrapping the Pagiflow core.
 *
 * @example
 * <Pagiflow loop nav paginate onSlideChange={setIdx}>
 *   <PagiflowSlide><img src="..." /></PagiflowSlide>
 *   <PagiflowSlide><img src="..." /></PagiflowSlide>
 * </Pagiflow>
 */
const Pagiflow = forwardRef((_a, ref) => {
    var { children, className, style, onSlideChange, renderNav, renderPagination, id, 
    // Extract all PagiflowOptions — anything left goes to the track div
    direction, fade, grid, gridColumns, gridFill, animate, itemsPerSlide, slidesToScroll, gap, height, startIndex, loop, speed, swipeThreshold, nav, navDisabledEnd, navigation, prevIcon, nextIcon, prevPosition, nextPosition, thumbnails, autoplay, autoplayDelay, pauseOnHover, paginate, paginationPosition, autoScroll, autoScrollSpeed, autoScrollDirection, lazyLoad, keyboard, centerMode, centerPadding, rtl, sync, responsive } = _a, rest = __rest(_a, ["children", "className", "style", "onSlideChange", "renderNav", "renderPagination", "id", "direction", "fade", "grid", "gridColumns", "gridFill", "animate", "itemsPerSlide", "slidesToScroll", "gap", "height", "startIndex", "loop", "speed", "swipeThreshold", "nav", "navDisabledEnd", "navigation", "prevIcon", "nextIcon", "prevPosition", "nextPosition", "thumbnails", "autoplay", "autoplayDelay", "pauseOnHover", "paginate", "paginationPosition", "autoScroll", "autoScrollSpeed", "autoScrollDirection", "lazyLoad", "keyboard", "centerMode", "centerPadding", "rtl", "sync", "responsive"]);
    const trackRef = useRef(null);
    const instanceRef = useRef(null);
    const onSlideChangeRef = useRef(onSlideChange);
    const currentIndexRef = useRef(startIndex !== null && startIndex !== void 0 ? startIndex : 0);
    const [, setUiTick] = useState(0);
    // Keep callback ref fresh
    onSlideChangeRef.current = onSlideChange;
    // Collect all Pagiflow options into one object
    const buildOptions = useCallback(() => {
        const opts = {};
        if (direction !== undefined)
            opts.direction = direction;
        if (fade !== undefined)
            opts.fade = fade;
        if (grid !== undefined)
            opts.grid = grid;
        if (gridColumns !== undefined)
            opts.gridColumns = gridColumns;
        if (gridFill !== undefined)
            opts.gridFill = gridFill;
        if (animate !== undefined)
            opts.animate = animate;
        if (itemsPerSlide !== undefined)
            opts.itemsPerSlide = itemsPerSlide;
        if (slidesToScroll !== undefined)
            opts.slidesToScroll = slidesToScroll;
        if (gap !== undefined)
            opts.gap = gap;
        if (height !== undefined)
            opts.height = height;
        if (startIndex !== undefined)
            opts.startIndex = startIndex;
        if (loop !== undefined)
            opts.loop = loop;
        if (speed !== undefined)
            opts.speed = speed;
        if (swipeThreshold !== undefined)
            opts.swipeThreshold = swipeThreshold;
        if (nav !== undefined)
            opts.nav = nav;
        if (navDisabledEnd !== undefined)
            opts.navDisabledEnd = navDisabledEnd;
        if (navigation !== undefined)
            opts.navigation = navigation;
        if (prevIcon !== undefined)
            opts.prevIcon = prevIcon;
        if (nextIcon !== undefined)
            opts.nextIcon = nextIcon;
        if (prevPosition !== undefined)
            opts.prevPosition = prevPosition;
        if (nextPosition !== undefined)
            opts.nextPosition = nextPosition;
        if (thumbnails !== undefined)
            opts.thumbnails = thumbnails;
        if (autoplay !== undefined)
            opts.autoplay = autoplay;
        if (autoplayDelay !== undefined)
            opts.autoplayDelay = autoplayDelay;
        if (pauseOnHover !== undefined)
            opts.pauseOnHover = pauseOnHover;
        if (paginate !== undefined)
            opts.paginate = paginate;
        if (paginationPosition !== undefined)
            opts.paginationPosition = paginationPosition;
        if (autoScroll !== undefined)
            opts.autoScroll = autoScroll;
        if (autoScrollSpeed !== undefined)
            opts.autoScrollSpeed = autoScrollSpeed;
        if (autoScrollDirection !== undefined)
            opts.autoScrollDirection = autoScrollDirection;
        if (lazyLoad !== undefined)
            opts.lazyLoad = lazyLoad;
        if (keyboard !== undefined)
            opts.keyboard = keyboard;
        if (centerMode !== undefined)
            opts.centerMode = centerMode;
        if (centerPadding !== undefined)
            opts.centerPadding = centerPadding;
        if (rtl !== undefined)
            opts.rtl = rtl;
        if (sync !== undefined)
            opts.sync = sync;
        if (responsive !== undefined)
            opts.responsive = responsive;
        return opts;
    }, [
        // Only recreate buildOptions when the serialized options change
        // eslint-disable-next-line react-hooks/exhaustive-deps
        JSON.stringify({
            direction, fade, grid, gridColumns, gridFill, animate, itemsPerSlide,
            slidesToScroll, gap, height, startIndex, loop, speed, swipeThreshold,
            nav, navDisabledEnd, navigation, prevIcon, nextIcon, prevPosition,
            nextPosition, thumbnails, autoplay, autoplayDelay, pauseOnHover,
            paginate, paginationPosition, autoScroll, autoScrollSpeed,
            autoScrollDirection, lazyLoad, keyboard, centerMode, centerPadding,
            rtl, sync, responsive,
        })
    ]);
    // ─── Init ──────────────────────────────────────────────────────────────────
    useEffect(() => {
        const el = trackRef.current;
        if (!el)
            return;
        const existing = el.pagiflowInstance;
        if (existing && !existing.destroyed)
            return;
        // Save complete pristine React DOM state
        const originalChildren = Array.from(el.children);
        const originalClasses = el.className;
        const originalStyle = el.getAttribute('style');
        const PagiflowCtor = getPagiflow$1();
        if (!PagiflowCtor) {
            console.error('[Pagiflow] Core not found. Install pagiflow or load it via CDN.');
            return;
        }
        const inst = initPagiflowFromElement$1(PagiflowCtor, el, buildOptions());
        if (!inst)
            return;
        el.pagiflowInstance = inst;
        const syncLayout = () => {
            var _a;
            const api = inst;
            (_a = api.update) === null || _a === void 0 ? void 0 : _a.call(api);
        };
        // Ensure correct sizing after React paints and fonts/layout settle.
        const raf1 = window.requestAnimationFrame(() => syncLayout());
        const raf2 = window.requestAnimationFrame(() => syncLayout());
        const timeoutId = window.setTimeout(() => syncLayout(), 80);
        window.addEventListener('load', syncLayout, { once: true });
        let resizeObserver = null;
        if (typeof ResizeObserver !== 'undefined') {
            resizeObserver = new ResizeObserver(() => syncLayout());
            resizeObserver.observe(el);
        }
        inst.onSlideChange((idx) => {
            var _a;
            currentIndexRef.current = idx;
            (_a = onSlideChangeRef.current) === null || _a === void 0 ? void 0 : _a.call(onSlideChangeRef, idx);
            if (renderNav || renderPagination) {
                setUiTick((n) => n + 1);
            }
        });
        instanceRef.current = inst;
        if (renderNav || renderPagination) {
            setUiTick((n) => n + 1);
        }
        return () => {
            window.cancelAnimationFrame(raf1);
            window.cancelAnimationFrame(raf2);
            window.clearTimeout(timeoutId);
            window.removeEventListener('load', syncLayout);
            resizeObserver === null || resizeObserver === void 0 ? void 0 : resizeObserver.disconnect();
            if (instanceRef.current && !instanceRef.current.destroyed) {
                try {
                    instanceRef.current.destroy();
                }
                catch ( /* ignore */_a) { /* ignore */ }
            }
            delete el.pagiflowInstance;
            instanceRef.current = null;
            // Fully restore DOM to pristine React state
            el.innerHTML = '';
            originalChildren.forEach(child => el.appendChild(child));
            el.className = originalClasses;
            if (originalStyle !== null) {
                el.setAttribute('style', originalStyle);
            }
            else {
                el.removeAttribute('style');
            }
            el.removeAttribute('data-pagiflow-react-id');
            delete el.dataset.pagiflowDestroyed;
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);
    // Keep core options in sync with prop changes after initial mount.
    useEffect(() => {
        if (!instanceRef.current || instanceRef.current.destroyed)
            return;
        instanceRef.current.setOptions(buildOptions(), true);
    }, [buildOptions]);
    // ─── Imperative API ────────────────────────────────────────────────────────
    useImperativeHandle(ref, () => ({
        get instance() { return instanceRef.current; },
        next: () => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.next(); },
        prev: () => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.prev(); },
        goTo: (i, o) => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.goTo(i, o); },
        play: () => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.play(); },
        pause: () => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.pause(); },
        resume: () => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.resume(); },
        togglePlayPause: () => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.togglePlayPause(); },
        setOptions: (o, r) => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.setOptions(o, r); },
        reInit: (o) => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.reInit(o); },
    }), []);
    // ─── Helpers ───────────────────────────────────────────────────────────────
    const next = useCallback(() => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.next(); }, []);
    const prev = useCallback(() => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.prev(); }, []);
    const goTo = useCallback((i, o) => { var _a; return (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.goTo(i, o); }, []);
    // Count real slides (ignore non-element children)
    const slideCount = Children.count(Children.toArray(children).filter(isValidElement));
    return (jsxs(Fragment, { children: [jsx("div", Object.assign({ ref: trackRef, id: id, className: ['pagiflow', className].filter(Boolean).join(' '), style: style }, rest, { children: children })), renderNav &&
                renderNav({
                    next,
                    prev,
                    currentIndex: currentIndexRef.current,
                    instance: instanceRef.current,
                }), renderPagination &&
                renderPagination({
                    goTo: (i) => goTo(i),
                    currentIndex: currentIndexRef.current,
                    total: slideCount,
                    instance: instanceRef.current,
                })] }));
});
Pagiflow.displayName = 'Pagiflow';

// ─── Pagiflow loader ─────────────────────────────────────────────────────────
// Resolves the Pagiflow constructor from window (CDN) or require('pagiflow')
function getPagiflow() {
    var _a;
    if (typeof window !== 'undefined' && window.Pagiflow) {
        return window.Pagiflow;
    }
    return (_a = PagiflowCore.default) !== null && _a !== void 0 ? _a : PagiflowCore;
}
function initPagiflowFromElement(ctor, el, opts) {
    const attrValue = `pf-${Math.random().toString(36).slice(2)}`;
    const selector = `[data-pagiflow-react-id="${attrValue}"]`;
    el.setAttribute('data-pagiflow-react-id', attrValue);
    const bySelector = ctor(selector, opts);
    if (!bySelector) {
        el.removeAttribute('data-pagiflow-react-id');
        return null;
    }
    return bySelector;
}
// ─── usePagiflow ─────────────────────────────────────────────────────────────
/**
 * Core hook to initialize and control a Pagiflow slider.
 *
 * @example
 * const { sliderRef, next, prev, currentIndex } = usePagiflow({ loop: true, nav: true });
 * return (
 *   <div ref={sliderRef as React.Ref<HTMLDivElement>}>
 *     <div>Slide 1</div>
 *     <div>Slide 2</div>
 *   </div>
 * );
 */
function usePagiflow(options = {}) {
    var _a;
    const sliderRef = useRef(null);
    const instanceRef = useRef(null);
    const optionsRef = useRef(options);
    const [currentIndex, setCurrentIndex] = useState((_a = options.startIndex) !== null && _a !== void 0 ? _a : 0);
    const [, forceUpdate] = useState(0);
    // Keep options ref in sync without triggering re-init
    optionsRef.current = options;
    // ─── Initialize ────────────────────────────────────────────────────────────
    useEffect(() => {
        const el = sliderRef.current;
        if (!el)
            return;
        const existing = el.pagiflowInstance;
        if (existing && !existing.destroyed)
            return;
        // Save complete pristine React DOM state
        const originalChildren = Array.from(el.children);
        const originalClasses = el.className;
        const originalStyle = el.getAttribute('style');
        let inst;
        const Pagiflow = getPagiflow();
        if (!Pagiflow) {
            console.error('[usePagiflow] Pagiflow core not found. Install pagiflow or load it via CDN.');
            return;
        }
        inst = initPagiflowFromElement(Pagiflow, el, optionsRef.current);
        if (!inst)
            return;
        el.pagiflowInstance = inst;
        const syncLayout = () => {
            var _a;
            const api = inst;
            (_a = api.update) === null || _a === void 0 ? void 0 : _a.call(api);
        };
        const raf1 = window.requestAnimationFrame(() => syncLayout());
        const raf2 = window.requestAnimationFrame(() => syncLayout());
        const timeoutId = window.setTimeout(() => syncLayout(), 80);
        window.addEventListener('load', syncLayout, { once: true });
        let resizeObserver = null;
        if (typeof ResizeObserver !== 'undefined') {
            resizeObserver = new ResizeObserver(() => syncLayout());
            resizeObserver.observe(el);
        }
        // Track slide changes
        inst.onSlideChange((idx) => {
            setCurrentIndex(idx);
        });
        instanceRef.current = inst;
        forceUpdate((n) => n + 1); // expose instance to consumers
        return () => {
            window.cancelAnimationFrame(raf1);
            window.cancelAnimationFrame(raf2);
            window.clearTimeout(timeoutId);
            window.removeEventListener('load', syncLayout);
            resizeObserver === null || resizeObserver === void 0 ? void 0 : resizeObserver.disconnect();
            if (instanceRef.current && !instanceRef.current.destroyed) {
                try {
                    instanceRef.current.destroy();
                }
                catch (_a) {
                    // ignore destroy errors on unmount
                }
            }
            delete el.pagiflowInstance;
            instanceRef.current = null;
            // Fully restore DOM to pristine React state
            el.innerHTML = '';
            originalChildren.forEach(child => el.appendChild(child));
            el.className = originalClasses;
            if (originalStyle !== null) {
                el.setAttribute('style', originalStyle);
            }
            else {
                el.removeAttribute('style');
            }
            el.removeAttribute('data-pagiflow-react-id');
            delete el.dataset.pagiflowDestroyed;
        };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []); // intentionally empty — init once on mount
    // ─── Stable API ────────────────────────────────────────────────────────────
    const goTo = useCallback((index, opts) => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.goTo(index, opts);
    }, []);
    const next = useCallback(() => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.next();
    }, []);
    const prev = useCallback(() => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.prev();
    }, []);
    const play = useCallback(() => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.play();
    }, []);
    const pause = useCallback(() => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.pause();
    }, []);
    const resume = useCallback(() => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.resume();
    }, []);
    const togglePlayPause = useCallback(() => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.togglePlayPause();
    }, []);
    const setOptions = useCallback((opts, rebuild = false) => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.setOptions(opts, rebuild);
    }, []);
    const reInit = useCallback((opts = {}) => {
        var _a;
        (_a = instanceRef.current) === null || _a === void 0 ? void 0 : _a.reInit(opts);
    }, []);
    return {
        sliderRef,
        instance: instanceRef.current,
        currentIndex,
        goTo,
        next,
        prev,
        play,
        pause,
        resume,
        togglePlayPause,
        setOptions,
        reInit,
    };
}

export { Pagiflow, PagiflowSlide, usePagiflow };
//# sourceMappingURL=index.esm.js.map

// packages/core/angular/index.esm.js
import 'pagiflow';
import { ViewChild, ElementRef, Input, Output, Component, ViewEncapsulation, Inject, PLATFORM_ID, EventEmitter, NgZone, Renderer2, inject, Injector, signal, effect, untracked, NgModule } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';

/******************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
/* global Reflect, Promise, SuppressedError, Symbol, Iterator */


function __decorate(decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
}

function __param(paramIndex, decorator) {
    return function (target, key) { decorator(target, key, paramIndex); }
}

function __metadata(metadataKey, metadataValue) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(metadataKey, metadataValue);
}

typeof SuppressedError === "function" ? SuppressedError : function (error, suppressed, message) {
    var e = new Error(message);
    return e.name = "SuppressedError", e.error = error, e.suppressed = suppressed, e;
};

// Pagiflow.ts
function getPagiflow$1() {
    var _a;
    if (typeof window !== 'undefined' && window.Pagiflow) {
        return window.Pagiflow;
    }
    try {
        const mod = require('pagiflow');
        return ((_a = mod.default) !== null && _a !== void 0 ? _a : mod);
    }
    catch (_b) {
        return null;
    }
}
function initPagiflowFromElement$1(ctor, el, opts, renderer) {
    const attrValue = `pf-${Math.random().toString(36).slice(2)}`;
    const selector = `[data-pagiflow-angular-id="${attrValue}"]`;
    renderer.setAttribute(el, 'data-pagiflow-angular-id', attrValue);
    const bySelector = ctor(selector, opts);
    if (!bySelector) {
        renderer.removeAttribute(el, 'data-pagiflow-angular-id');
        return null;
    }
    return bySelector;
}
// ─── Pagiflow Component ───────────────────────────────────────────────────────
let PagiflowComponent = class PagiflowComponent {
    constructor(platformId, ngZone, renderer) {
        this.platformId = platformId;
        this.ngZone = ngZone;
        this.renderer = renderer;
        // Input options
        this.options = {};
        // Output events
        this.slideChange = new EventEmitter();
        this.ready = new EventEmitter();
        this.instance = null;
        this.resizeObserver = null;
        this.raf1 = 0;
        this.raf2 = 0;
    }
    ngAfterViewInit() {
        this.initPagiflow();
    }
    ngOnDestroy() {
        this.destroy();
    }
    initPagiflow() {
        if (!isPlatformBrowser(this.platformId))
            return;
        const el = this.trackRef.nativeElement;
        const existing = el.pagiflowInstance;
        let inst = null;
        if (existing && !existing.destroyed) {
            inst = existing;
        }
        else {
            const ctor = getPagiflow$1();
            if (!ctor) {
                console.error('[PagiflowComponent] Pagiflow core not found. Install pagiflow or load it via CDN.');
                return;
            }
            inst = initPagiflowFromElement$1(ctor, el, this.options, this.renderer);
        }
        if (!inst)
            return;
        this.instance = inst;
        el.pagiflowInstance = inst;
        this.ready.emit(inst);
        // Listen to slide changes via the instance API
        inst.onSlideChange((idx) => {
            this.ngZone.run(() => {
                this.slideChange.emit(idx);
            });
        });
        // Setup resize observer for responsive behavior
        this.ngZone.runOutsideAngular(() => {
            this.resizeObserver = new ResizeObserver(() => {
                cancelAnimationFrame(this.raf1);
                this.raf1 = requestAnimationFrame(() => {
                    cancelAnimationFrame(this.raf2);
                    this.raf2 = requestAnimationFrame(() => {
                        if (this.instance)
                            this.instance.reInit();
                    });
                });
            });
            this.resizeObserver.observe(el);
        });
    }
    destroy() {
        if (this.resizeObserver) {
            this.resizeObserver.disconnect();
            this.resizeObserver = null;
        }
        cancelAnimationFrame(this.raf1);
        cancelAnimationFrame(this.raf2);
        if (this.instance && !this.instance.destroyed) {
            this.instance.destroy();
        }
        this.instance = null;
    }
    // Public API methods
    /**
     * Get the underlying Pagiflow instance.
     */
    getInstance() {
        return this.instance;
    }
    /**
     * Navigate to the next slide.
     */
    next() {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.next();
    }
    /**
     * Navigate to the previous slide.
     */
    prev() {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.prev();
    }
    /**
     * Go to a specific slide index.
     */
    goTo(index, opts) {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.goTo(index, opts);
    }
    /**
     * Start autoScroll.
     */
    play() {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.play();
    }
    /**
     * Pause autoScroll.
     */
    pause() {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.pause();
    }
    /**
     * Resume autoScroll after pause.
     */
    resume() {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.resume();
    }
    /**
     * Toggle autoScroll play/pause state.
     */
    togglePlayPause() {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.togglePlayPause();
    }
    /**
     * Update options and optionally rebuild.
     */
    setOptions(opts, rebuild) {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.setOptions(opts, rebuild);
    }
    /**
     * Reinitialize with new or updated options.
     */
    reInit(opts) {
        var _a;
        (_a = this.instance) === null || _a === void 0 ? void 0 : _a.reInit(opts);
    }
};
__decorate([
    ViewChild('track', { read: ElementRef }),
    __metadata("design:type", ElementRef)
], PagiflowComponent.prototype, "trackRef", void 0);
__decorate([
    Input(),
    __metadata("design:type", Object)
], PagiflowComponent.prototype, "options", void 0);
__decorate([
    Input(),
    __metadata("design:type", String)
], PagiflowComponent.prototype, "className", void 0);
__decorate([
    Input(),
    __metadata("design:type", Object)
], PagiflowComponent.prototype, "style", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], PagiflowComponent.prototype, "slideChange", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], PagiflowComponent.prototype, "ready", void 0);
PagiflowComponent = __decorate([
    Component({
        selector: 'pf-pagiflow',
        standalone: true,
        imports: [CommonModule],
        template: `
    <div
      #track
      [ngClass]="['pf-track', className || '']"
      [style]="style"
    >
      <ng-content></ng-content>
    </div>
  `,
        encapsulation: ViewEncapsulation.None,
    }),
    __param(0, Inject(PLATFORM_ID)),
    __metadata("design:paramtypes", [Object,
        NgZone,
        Renderer2])
], PagiflowComponent);
// ─── Pagiflow Slide Component ─────────────────────────────────────────────────
let PagiflowSlideComponent = class PagiflowSlideComponent {
};
__decorate([
    Input(),
    __metadata("design:type", String)
], PagiflowSlideComponent.prototype, "className", void 0);
__decorate([
    Input(),
    __metadata("design:type", Object)
], PagiflowSlideComponent.prototype, "style", void 0);
PagiflowSlideComponent = __decorate([
    Component({
        selector: 'pf-slide',
        standalone: true,
        template: `<ng-content></ng-content>`,
        host: {
            'class': 'pf-slide',
            '[class]': 'className',
            '[style]': 'style'
        },
        encapsulation: ViewEncapsulation.None,
    })
], PagiflowSlideComponent);

// usePagiflow.ts
function getPagiflow() {
    var _a;
    if (typeof window !== 'undefined' && window.Pagiflow) {
        return window.Pagiflow;
    }
    try {
        const mod = require('pagiflow');
        return ((_a = mod.default) !== null && _a !== void 0 ? _a : mod);
    }
    catch (_b) {
        return null;
    }
}
function initPagiflowFromElement(ctor, el, opts) {
    const attrValue = `pf-${Math.random().toString(36).slice(2)}`;
    const selector = `[data-pagiflow-angular-id="${attrValue}"]`;
    el.setAttribute('data-pagiflow-angular-id', attrValue);
    const bySelector = ctor(selector, opts);
    if (!bySelector) {
        el.removeAttribute('data-pagiflow-angular-id');
        return null;
    }
    return bySelector;
}
/**
 * Angular composable (using signals) for Pagiflow slider integration.
 * Usage:
 *   export class SliderComponent {
 *     pagi = usePagiflow({ direction: 'horizontal' });
 *
 *     onMount() {
 *       this.pagi.sliderRef.set(this.elementRef.nativeElement);
 *     }
 *   }
 */
function usePagiflow(options = {}) {
    var _a;
    inject(Injector);
    const sliderRef = signal(null);
    const instance = signal(null);
    const currentIndex = signal((_a = options.startIndex) !== null && _a !== void 0 ? _a : 0);
    let resizeObserver = null;
    let raf1 = 0;
    let raf2 = 0;
    let timeoutId = 0;
    // Setup effect to initialize Pagiflow when sliderRef changes
    effect(() => {
        const el = sliderRef();
        if (!el)
            return;
        const existing = el.pagiflowInstance;
        if (existing && !existing.destroyed) {
            instance.set(existing);
            return;
        }
        const ctor = getPagiflow();
        if (!ctor) {
            console.error('[usePagiflow] Pagiflow core not found. Install pagiflow or load it via CDN.');
            return;
        }
        const inst = initPagiflowFromElement(ctor, el, options);
        if (!inst)
            return;
        instance.set(inst);
        el.pagiflowInstance = inst;
        // Setup resize observer
        resizeObserver = new ResizeObserver(() => {
            cancelAnimationFrame(raf1);
            raf1 = requestAnimationFrame(() => {
                cancelAnimationFrame(raf2);
                raf2 = requestAnimationFrame(() => {
                    inst.reInit();
                });
            });
        });
        resizeObserver.observe(el);
        // Listen to slide changes via instance API
        inst.onSlideChange((idx) => {
            currentIndex.set(idx);
        });
        return () => {
            cleanup();
            if (inst && !inst.destroyed)
                inst.destroy();
            instance.set(null);
        };
    });
    const cleanup = () => {
        if (resizeObserver) {
            resizeObserver.disconnect();
            resizeObserver = null;
        }
        cancelAnimationFrame(raf1);
        cancelAnimationFrame(raf2);
        clearTimeout(timeoutId);
    };
    const goTo = (index, opts) => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.goTo(index, opts);
    };
    const next = () => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.next();
    };
    const prev = () => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.prev();
    };
    const play = () => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.play();
    };
    const pause = () => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.pause();
    };
    const togglePlayPause = () => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.togglePlayPause();
    };
    const setOptions = (opts, rebuild) => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.setOptions(opts, rebuild);
    };
    const reInit = (opts) => {
        const inst = untracked(() => instance());
        inst === null || inst === void 0 ? void 0 : inst.reInit(opts);
    };
    return {
        sliderRef,
        instance,
        currentIndex,
        goTo,
        next,
        prev,
        play,
        pause,
        togglePlayPause,
        setOptions,
        reInit,
    };
}

let PagiflowModule = class PagiflowModule {
};
PagiflowModule = __decorate([
    NgModule({
        imports: [PagiflowComponent, PagiflowSlideComponent],
        exports: [PagiflowComponent, PagiflowSlideComponent],
    })
], PagiflowModule);

export { PagiflowComponent, PagiflowModule, PagiflowSlideComponent, usePagiflow };
//# sourceMappingURL=index.esm.js.map
